"""Check actual evidence paths generated by relevance.py"""
import sys
from pathlib import Path

# Add backend to path
sys.path.insert(0, str(Path("D:/hack26/src/backend")))

from app.domain import index, relevance

# Load dataset
dataset = index.load(force=True)

# Check all findings for the 8 problem portfolios
problem_portfolios = [
    ("CASE-001", "CASE-001-01"),
    ("CASE-006", "CASE-006-02"),
    ("CASE-006", "CASE-006-03"),
    ("CASE-014", "CASE-014-01"),
    ("CASE-021", "CASE-021-02"),
    ("CASE-025", "CASE-025-01"),
    ("CASE-036", "CASE-036-02"),
    ("CASE-046", "CASE-046-01"),
]

print("=" * 80)
print("Evidence paths for problem portfolios")
print("=" * 80)

for client_ref, portfolio_nr in problem_portfolios:
    findings = relevance.findings(client_ref, portfolio_nr)
    print(f"\n{client_ref} / {portfolio_nr}: {len(findings)} findings")
    for f in findings:
        print(f"  [{f['type']}] severity={f['severity']}, score={f['score']:.2f}")
        for e in f['evidence']:
            path = e['path']
            value = e['value']
            source = e['source']
            # Check for problematic patterns
            issues = []
            if "[]" in path:
                issues.append("WILDCARD")
            if "[-" in path:
                issues.append("NEGATIVE_INDEX")
            if "SecurityPositions" in path and source == "clients.json":
                # Check if this portfolio actually has SecurityPositions
                client = dataset.client(client_ref)
                portfolio = next((p for p in client.get("Portfolios", []) if p.get("PortfolioNr") == portfolio_nr), None)
                if portfolio and "SecurityPositions" not in portfolio:
                    issues.append("MISSING_KEY")
            if issues:
                print(f"    *** {', '.join(issues)}: {path} = {value}")
            else:
                print(f"    OK: {path} = {value}")

# Check stale_data paths
print("\n" + "=" * 80)
print("Stale data evidence paths")
print("=" * 80)

# Find a client with stale data
for client_ref in ["CASE-001", "CASE-002", "CASE-003"]:
    findings = relevance.findings(client_ref)
    stale = [f for f in findings if f['type'] == 'stale_data']
    if stale:
        print(f"\n{client_ref}:")
        for f in stale:
            for e in f['evidence']:
                print(f"  {e['path']} = {e['value']}")

# Check open_proposal for the 5 draft clients
print("\n" + "=" * 80)
print("Open proposal evidence paths")
print("=" * 80)

draft_clients = ["CASE-017", "CASE-034", "CASE-037", "CASE-042", "CASE-045"]

for client_ref in draft_clients:
    findings = relevance.findings(client_ref)
    open_props = [f for f in findings if f['type'] == 'open_proposal']
    print(f"\n{client_ref}: {len(open_props)} open_proposal findings")
    for f in open_props:
        print(f"  severity={f['severity']}, score={f['score']:.2f}")
        for e in f['evidence']:
            print(f"    {e['path']} = {e['value']}")
