import type { Lang } from '../../i18n';

/**
 * Bilingual strings for the Fremdbanken (external custody) screen.
 * German values are copied verbatim from the original monolingual UI.
 */
export const fremdbankenStrings = {
  en: {
    back: '← Back',
    bankName: 'Privatbank Helvetia AG',
    title: 'External Custody Banks',
    titleFallback: 'External Custody Portfolio',
    declarationTitle: 'Third-party custody account · Fictional data for demonstration purposes',
    declarationBody:
      'This portfolio was imported from an external client report and does not originate from our own custody administration. The data is provided for demonstration purposes only.',
    reportsLoadError: 'Error loading reports:',
    file: 'File',
    portfolioNr: 'Portfolio No.',
    importError: 'Import error:',
    alreadyImported: 'Report already imported as {nr} from {file}. Delete the existing import before importing the same statement again.',
    selectReport: 'Select Report',
    availableReports: 'Available Reports ({count})',
    pages: 'pages',
    importing: 'Importing report…',
    uploadTitle: 'Or upload a statement',
    uploadHint: 'Upload a PDF statement from another custodian. It is parsed into a virtual portfolio that behaves like a native one.',
    uploadButton: 'Choose PDF',
    uploading: 'Reading the statement…',
    uploaded: 'Uploaded',
    unreadablePdf: 'The file could not be read as a PDF — it may be damaged, password-protected or not a PDF at all.',
    noPositionsImported: 'No positions could be read from this statement, so nothing was imported.',
    kpi: 'Key Figures',
    keyDate: 'Key Date',
    reportingCurrency: 'Reporting Currency',
    positions: 'Positions',
    transactions: 'Transactions',
    assetsAsOfKeyDate: 'Assets as of Key Date',
    performance2025: 'Performance 2025 (TWR, net)',
    deltaPositionsVsReport: 'Delta Positions vs. Report',
    currencyStructure: 'Asset Structure by Currency',
    noCurrencyStructure: 'No currency structure available.',
    detailPositions: 'Detail Positions',
    noPositions: 'No positions available.',
    isinsMatched: '{count} ISIN recorded',
    isinsUnknown: '{count} unknown',
    noTransactions: 'No transactions available.',
    dataQualityNotes: 'Data Quality Notes',
    colPosition: 'Position',
    colIsinValor: 'ISIN / Valor',
    colCurrency: 'Ccy',
    colQuantity: 'Quantity',
    colMarketPrice: 'Market Price',
    colCostPrice: 'Cost Price',
    colWeight: 'Weight',
    colStatus: 'Status',
    colCurrencyCode: 'Currency',
    colName: 'Name',
    colLiquidity: 'Liquidity',
    colBonds: 'Bonds',
    colShares: 'Shares',
    colAlternatives: 'Alternatives',
    colTotal: 'Total',
    colType: 'Type',
    colDescription: 'Description',
    colDate: 'Date',
    colAmountChf: 'Amount (CHF)',
    colCostIncome: 'Expense / Income',
    statusRecorded: '✓ Recorded',
    statusUnknown: '? Unknown',
    txBuy: 'Buy',
    txSell: 'Sell',
    txDividend: 'Dividend',
    txCoupon: 'Coupon',
    txCustodyFees: 'Custody Fees',
    txInflow: 'Inflow',
    pageChip: 'P. {page}',
    valorLabel: 'Valor {valor}',
    cash: 'Cash',
  },
  de: {
    back: '← Zurück',
    bankName: 'Privatbank Helvetia AG',
    title: 'Fremdbanken',
    titleFallback: 'Fremdbanken-Portfolio',
    declarationTitle: 'Drittanbieter-Depot · Fiktive Daten zu Demonstrationszwecken',
    declarationBody:
      'Dieses Portfolio wurde aus einem externen Kundenreport importiert und stammt nicht aus unserer eigenen Depotverwaltung. Die Daten dienen ausschliesslich Demonstrationszwecken.',
    reportsLoadError: 'Fehler beim Laden der Reporte:',
    file: 'Datei',
    portfolioNr: 'Portfolio-Nr',
    importError: 'Fehler beim Import:',
    alreadyImported: 'Report bereits als {nr} aus {file} importiert. Bestehenden Import löschen, bevor derselbe Auszug erneut importiert wird.',
    selectReport: 'Report auswählen',
    availableReports: 'Verfügbare Reporte ({count})',
    pages: 'Seiten',
    importing: 'Report wird importiert…',
    uploadTitle: 'Oder Auszug hochladen',
    uploadHint: 'Laden Sie einen PDF-Auszug einer anderen Depotbank hoch. Er wird in ein virtuelles Portfolio überführt, das sich wie ein natives verhält.',
    uploadButton: 'PDF auswählen',
    uploading: 'Auszug wird gelesen…',
    uploaded: 'Hochgeladen',
    unreadablePdf: 'Die Datei konnte nicht als PDF gelesen werden — sie ist möglicherweise beschädigt, passwortgeschützt oder kein PDF.',
    noPositionsImported: 'Aus diesem Auszug konnten keine Positionen gelesen werden; es wurde nichts importiert.',
    kpi: 'Kennzahlen',
    keyDate: 'Stichtag',
    reportingCurrency: 'Berichtswährung',
    positions: 'Positionen',
    transactions: 'Transaktionen',
    assetsAsOfKeyDate: 'Vermögen per Stichtag',
    performance2025: 'Performance 2025 (TWR, netto)',
    deltaPositionsVsReport: 'Differenz Positionen vs. Report',
    currencyStructure: 'Vermögensstruktur nach Währung',
    noCurrencyStructure: 'Keine Währungsstruktur verfügbar.',
    detailPositions: 'Detailpositionen',
    noPositions: 'Keine Positionen verfügbar.',
    isinsMatched: '{count} ISIN erfasst',
    isinsUnknown: '{count} unbekannt',
    noTransactions: 'Keine Transaktionen verfügbar.',
    dataQualityNotes: 'Hinweise zur Datenqualität',
    colPosition: 'Position',
    colIsinValor: 'ISIN / Valor',
    colCurrency: 'Whg',
    colQuantity: 'Stück',
    colMarketPrice: 'Marktkurs',
    colCostPrice: 'Einstand',
    colWeight: 'Anteil',
    colStatus: 'Status',
    colCurrencyCode: 'Währung',
    colName: 'Name',
    colLiquidity: 'Liquidität',
    colBonds: 'Obligationen',
    colShares: 'Aktien',
    colAlternatives: 'Alternativen',
    colTotal: 'Total',
    colType: 'Typ',
    colDescription: 'Bezeichnung',
    colDate: 'Datum',
    colAmountChf: 'Betrag (CHF)',
    colCostIncome: 'Aufwand / Ertrag',
    statusRecorded: '✓ Erfasst',
    statusUnknown: '? Unbekannt',
    txBuy: 'Kauf',
    txSell: 'Verkauf',
    txDividend: 'Dividende',
    txCoupon: 'Coupon',
    txCustodyFees: 'Depotgebühren',
    txInflow: 'Zufluss',
    pageChip: 'S. {page}',
    valorLabel: 'Valor {valor}',
    cash: 'Cash',
  },
} as const;

export type FremdbankenStrings = Record<keyof (typeof fremdbankenStrings)['en'], string>;

/** Resolve the Fremdbanken string table for the given language. */
export const fremdbankenStringsFor = (lang: Lang): FremdbankenStrings =>
  fremdbankenStrings[lang] ?? fremdbankenStrings.en;
