"""Response models for the F2/F3/F4 HTTP contract.

This module is the backend half of the frontend↔backend contract; ``frontend/src/types.ts`` mirrors
it. Change one, change the other. Deep, self-describing structures (SAA rows, positions, exposures,
rail widgets) stay as ``dict`` on purpose — they are generated by ``app.domain`` and documented in
``notes-task/PROJECT.md`` §5.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class Tab(BaseModel):
    """A filter tab on the advisor dashboard, with a count computed from real data."""

    id: str
    label: str
    count: int
    hint: str | None = None
    supported: bool = True


class Money(BaseModel):
    currency: str
    amount: float


class ClientRow(BaseModel):
    ref: str
    client_id: int | None
    name: str
    type: str | None
    is_company: bool
    reporting_currency: str | None
    aum: float
    liquidity_pct: float | None
    birthday: str | None
    days_to_birthday: int | None
    profiling_date: str | None
    last_changed: str | None
    last_consultation: str | None
    last_consultation_basis: str
    portfolio_count: int
    external_portfolio_count: int = 0
    external_aum: float = 0.0
    violation_count: int
    warning_count: int
    has_violation: bool
    has_warning: bool
    has_maturities: bool
    street: str | None = None
    zip: str | None = None
    city: str | None = None
    data_gaps: list[str] = Field(default_factory=list)


class ClientsResponse(BaseModel):
    advisor: dict
    book_total: Money
    data_as_of: str | None
    counts: dict[str, int]
    tabs: list[Tab]
    rows: list[ClientRow]
    integrity: dict
    notes: list[str] = Field(default_factory=list)
    lang: str = "en"

class ClientDetailResponse(BaseModel):
    client: dict
    portfolios: list[dict]
    proposals: list[dict]
    violations: list[dict]
    notes: list[dict]
    tags: dict
    overrides: list[dict]
    counts: dict
    data_gaps: list[str] = Field(default_factory=list)
    lang: str = "en"


class PortfolioDetailResponse(BaseModel):
    client: dict
    portfolio: dict
    saa: dict
    positions: list[dict]
    groups: list[dict]
    total: dict
    exposures: dict
    fx: dict
    prc: dict
    sustainability: dict
    maturity: dict
    metrics: list[dict]
    violations: list[dict]
    integrity: dict
    data_gaps: list[str] = Field(default_factory=list)
    lang: str = "en"
